### ISSUE TITLE
Wrong timestamps in TIFFs

### ISSUE THREAD

**Issue by rokubun** [micasense/rededge-api#1]
We acquired data using MicaSense Rededge connected to a U-Blox Neo M8T. If I look into the TIFF's metadata I can find the geo-tags, as well as the time information.

For some images though, the temporal information seems to be incorrect. Specifically, I have encountered negative values in the floating part (field Composite:SubSecModifyDate if reading the metadata with ExifTool). The rest of the timestamp makes sense (it is earlier than the one of the preceding image, and later than the leading one). 

This effect appears in bursts (e.g for images IMG_0025_[b].tif to IMG_0033_[b].tif) and at all the bands).

I am not sure how to interpret it, whether I should ignore the negative sign, or the whole fractonal part has to be ignored. 

Another error we have encountered is 2 images sharing the same timestamp, while the geo-tags are different. Any hint on that?

Thanks!

**Comment by poynting** [comment]
Hi @rokubun - How is the GPS information getting into the camera? Are you using the serial or network API to push PVT data into the camera, or is the uBlox receiver connected directly to the GPS port of the RedEdge?

**Comment by rokubun** [comment]
Hi Justin,Thanks for your mail.The Argonaut GNSS receiver is directly connected to the Rededge GPS port. Let us know if you need further detailsBestMiquelOn Sep 19, 2017 6:18 PM, "Justin M." <notifications@github.com> wrote:Hi @rokubun - How is the GPS information getting into the camera? Are you using the serial or network API to push PVT data into the camera, or is the uBlox receiver connected directly to the GPS port of the RedEdge?

**Comment by poynting** [comment]
OK thanks.  As since the operation of the GPS port isn't part of the public API, please contact support at micasense dot com and we'll try to help sort through your integration.
