### ISSUE TITLE
RedEdge API is applied to ALTUM？

### ISSUE THREAD

**Issue by du1970** [micasense/rededge-api#2]
if not, how to do? I want to control an ALTUM camera with my routing plan in android PAD.
Looking forward the answer.

**Comment by poynting** [comment]
Yes, the API is the same. Altum doesn't have hard-wired ethernet, but you can use a USB3.0 to ethernet converter or connect over WiFi and the API is the same as RedEdge.

**Comment by du1970** [comment]
thanks, @poynting , try to do it
